### ISSUE TITLE
Load minimal "resource identifier" object for relationships that are not loaded

### ISSUE THREAD

**Issue by wasnotrice** [jeregrine/jsonapi#108]
I was surprised that nothing is produced for a relationship that is not loaded. I expected that

* if I have a `belongs_to` field on my Ecto schema, and 
* the `relationships/0` function in my view includes that field, and
* the association is "not loaded",

then I would get a [resource identifier](http://jsonapi.org/format/#document-resource-identifier-objects) object that only contains the `type` and `id` of the related resource. Even though the association is not loaded, there is still enough information to generate the resource identifier.

Would you accept a PR that, instead of omitting "not loaded" associations from relationships, adds a minimal "resource identifier" object for them? Or are there other considerations I am missing? Thanks!

**Comment by doomspork** [comment]
@wasnotrice how do you intend to get the type and id without loading the associated resources?

**Comment by doomspork** [comment]
Why not just preload the association if you want the data populated?

**Comment by wasnotrice** [comment]
ok
