### ISSUE TITLE
Query parser plugability

### ISSUE THREAD

**Issue by zamith** [jeregrine/jsonapi#109]
I've using the QueryParser plug and it works fine, but there is something that is somewhat of an issue, since the options, namely `view` are fetched in the `init` function, they need to be passed at compile time. This makes it harder to use `Plug.Builder` and have another plug extend the QueryParser.

I'd like to be able to do:

```elixir
defmodule SuperQueryParser do
  use Plug.Builder

  plug JSONAPI.QueryParser

  def init(opts) do
    opts
  end

  def call(conn, opts) do
    conn = conn |> super(opts)
    ...
  end
end

defmodule App.SomeController do
  use App, :controller

  plug SuperQueryParser, view: App.SomeView
end
```

This would mean moving `build_config` to the `call` function instead. Is this something desirable or is there any other way to achieve the same behaviour?

**Comment by doomspork** [comment]
@zamith I don't quite follow this particular example.  What is `SuperQueryParser` intended to accomplish?  I can think of a few different approaches we could take here but I'm not entirely sure what you're hoping to accomplish.

**Comment by zamith** [comment]
Well, my exact use case is that I want to add some pagination stuff, particularly creating a Base64 encoded cursor based on some of the parameters that `JSONAPI.QueryParser` parses, and abstract that from the controller via a plug.

**Comment by doomspork** [comment]
I'm not sure moving `build_config/1` will do what you want.  🤔 

While it _might_ work I don't believe that is how Plug is intended to be used.  The `init/1` method is to initialize things such as `opts` much like we do with GenServers.   We should encourage good practices by default in the library.

I've done something akin to what you're doing but it wasn't possible without making use of `use`.

```elixir
defmodule Example.JSONAPI do
  defmacro __using__(opts) do
    view = Keyword.fetch!(opts, :view)

    quote do
      use Plug.Builder

      import JSONAPI.ErrorView

      require Logger

      plug Plug.RequestId
      plug Plug.Logger
      plug Plug.Parsers, parsers: [:json], pass: ["text/*"], json_decoder: Poison
      plug JSONAPI.EnsureSpec
      plug JSONAPI.QueryParser, view: unquote(view)
      plug :dispatch
    end
  end
end

```

**Comment by zamith** [comment]
Ah, nice. Was totally forgetting about metaprogramming. That should do it. Thanks.
