### ISSUE TITLE
Relationships appear incorrectly when not preloaded

### ISSUE THREAD

**Issue by mjc** [jeregrine/jsonapi#115]
`%{"data" => %{"id" => nil, "type" => "foo"}}` is the relationship linkage object when data is not preloaded, even for a one-to-one relationship where the id is known.

I don't know exactly what should be there (it's not really clear in the spec) but it seems not quite right to set id to nil regardless of what the correct action is.

**Comment by doomspork** [comment]
@mjc can you please provide code or an example project that reproduces this?

**Comment by jherdman** [comment]
@mjc did you resolve your issue, or are you able to help us reproduce this problem?

**Comment by jherdman** [comment]
@mjc I'm going to close this issue due to inactivity. Please feel free to reopen the issue should it continue to be a problem for you.
