### ISSUE TITLE
Support for heterogeneous collections?

### ISSUE THREAD

**Issue by wasnotrice** [jeregrine/jsonapi#118]
I am implementing a search endpoint, where the search may return different sorts of resources, as in [this scenario]((https://discuss.jsonapi.org/t/how-to-implement-a-search-api/35)). I don't think this is currently supported, is it?

Do you think this library should heterogenous collections , given that json:api supports them?

I'm not sure yet what would be the best approach to implementing, although I'd be happy to try a few things and see what works.

In the meantime can require multiple requests to perform a search as a workaround.

Cheers!

**Comment by jeregrine** [comment]
Can you link me to the specification where it describes that? I saw that you can post up non-heterogeneous data. I wish they provided a test suite :P

**Comment by wasnotrice** [comment]
I wish I could link to where it describes that in the spec 😬 but it is not explicitly stated. It follows from the description in [document structure(http://jsonapi.org/format/#document-structure). The only restriction on a "primary data" field is that it is either a resource object or an array of resource objects, where each resource object specifies its own type. Notably, I don't think the spec says anything about resource objects having to be the same type.

Some other mentions
- cited as a benefit of json:api in a [hacker news comment](https://news.ycombinator.com/item?id=9281102) by one of the spec authors
- mentioned in [a github issue](https://github.com/json-api/json-api/issues/278)

I agree, a test suite would be nice. Or even a few more examples.

**Comment by jeregrine** [comment]
Yea I think we could support it, I'm uncertain how specifically but I am
open to ideas/PR's.

**Comment by jeregrine** [comment]
The github references heterogenius linked collections which we support. 

I think maybe the way you could solve this is to have a new resource called SearchResult which has linked resources that represent the value. JSONAPI resources/view need not all be writeable or have models in the DB.

**Comment by wasnotrice** [comment]
Cool—I'll look into linked resources and see where that takes me. Thanks!

**Comment by jeregrine** [comment]
Yea sorry you'd have a Search Result, it would have linked resources that
are inncluded.

**Comment by wasnotrice** [comment]
Thanks for the push toward linked collections. I ended up making an endpoint `GET /search/:id`, where `id` is the url-encoded version of the search query. Responses have a has_many relationship for each resource type, and the resource objects (of various types) can be included in the top-level `included` field.

Closing this for now. Thanks again for the help!

**Comment by jeregrine** [comment]
Perfect!
