### ISSUE TITLE
Map with no atoms doesn't work

### ISSUE THREAD

**Issue by jnylen** [jeregrine/jsonapi#125]
Hi,
Let's say you have a map of:
`%{"foo" => "bar"}`

Then doing:
```elixir
fields do
 [:foo]
end
```
Won't work, even if you replace :foo with "foo".

As atoms aren't garbage collected, I hope we can get this supported rather that converting everything to atoms:
https://github.com/elixir-lang/elixir/issues/2915#issuecomment-65556180

**Comment by doomspork** [comment]
@jnylen atoms aren't garbage collected but via `fields/0` you have a static set, no additional memory would ever be allocated beyond the initial set.  I do not believe the inverse to be the same with respect to Strings.

**Comment by jnylen** [comment]
@doomspork,
True.

Problem here is that ArangoDB returns json and you can return it in any way you want.
So users can return such as "company", "companies" etc, which all adds up.

If you do a single repo "get" etc it will match to the struct, but doing a query it will return an map of string.
(This being Durango)

**Comment by jnylen** [comment]
@doomspork JFYI,
Durango returns both atoms and strings depending on what you use.
If I use their Repo.get(Model, id) they return atoms.

If I use the query such as:
```elixir
{:ok, %{"result" => results}} = Durango.query(
              for: user in :users,
              filter: username == ^username,
              return: user
            )
            |> Server.Repo.execute
```

It will return string as `return: user` can be `return: %{blablbalab: user}`

**Comment by jnylen** [comment]
@doomspork, @mitchellhenke, @snewcomer,
Any ETA on this?

**Comment by jeregrine** [comment]
@jnylen If you need it sooner than we are able to complete it, pull requests are gladly accepted. This is a fully volunteer effort and even though it was assigned, no timelines were promised.

**Comment by jnylen** [comment]
@jeregrine,

Sorry if I sounded like a dick. I have moved to GraphQL so I'll close this.
