### ISSUE TITLE
IdRequired matches literal "id" parameter, should be configurable

### ISSUE THREAD

**Issue by maltoe** [jeregrine/jsonapi#133]
Hi @jeregrine,

I have a nested resource in phoenix and my parameter is not called `id`, but `foo_id`. Would it be possible to make that configurable?

cheers,
malte

**Comment by snewcomer** [comment]
@maltoe Are you looking to change the top level member "id" to "foo_id"?  If so, I'm not totally sure that is kosher according to the specs for both the top level resource and nested resource.  The only case that makes "id" optional is creating resources on the client.  Let me know if you see anything different 👍 

Note - for using a slug as the id, this is what I put in the, e.g. `person_view.ex`.
```
def id(%Person{slug: slug}), do: slug
```

http://jsonapi.org/format/#document-resource-objects
http://jsonapi.org/format/#document-resource-identifier-objects

**Comment by maltoe** [comment]
Hey @snewcomer, no, I meant the second ´"id"´ parameter coming from phoenix. In my scenario, I had a nested custom `PUT` action in a controller (actually, this is probably the same for top-level resources) á la

```
resources("/foos", ...) do
  resources("/bars", BarController, ...) do
    put "/special_update", BarController, :special_submit
  end
end
```

... and I wanted to verify that the payload `id` is the same as the id passed in through the URL. Phoenix calls this param `bar_id` for this route (maybe top-level custom actions as well, not sure). However, it doesn't even error, but simply fallthrough to the last `call/2` clause in [here](https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/plugs/id_required.ex#L23). I wanted it to go to `mismatched_id` in [this one](https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/plugs/id_required.ex#L19), which it didn't since `"id"` is hard-coded.

Perhaps this is not intended use of the `IdRequired` plug, but I thought it should be pretty easy to make this `id` configurable.

Best,
Malte

**Comment by maltoe** [comment]
btw, Phoenix calls the option for the name of the id part of the URL `param`, see [here](https://hexdocs.pm/phoenix/Phoenix.Router.html#resources/3)

**Comment by maltoe** [comment]
and sorry for being so unclear in the first post, should have put more info in it :)

**Comment by doomspork** [comment]
@maltoe I think I'm following.  In a scenario where we have url: `/example/:id/nested_resource/:another_id`, you want the `IdRequired` plug to compare the payload `"id"` to the value of `:another_id`?

I think supporting this is reasonable but my only concern would be: is this valid in the eyes of the JSON API spec?  I can't find anything about nested resources, it seems to point towards relationships.

**Comment by maltoe** [comment]
@doomspork Yes. Question about the JSON API spec is excellent, I'm afraid my insight into that is too limited to be of any help here.

Most examples on `relationships` in the Spec seem to be based on a n-1 association (e.g. `/article/:id` is a resource object containing a relationship to an `author`). In our case the top-level resource is 1-n to the nested (e.g. company -> employee), and we're using the scoped route to identify the nested resource first on the top-level resource ID and second on the nested ID. Perhaps our routing is already anti-conventional and we should have kept the nested resource at top-level and its ID globally unique...

**Comment by doomspork** [comment]
@maltoe I believe this is how JSON API expect relationships to be queried: https://jsonapi.org/format/#fetching-relationships

**Comment by doomspork** [comment]
Howdy @maltoe! I wanted to touch base and see if you've had a chance to look at the JSON:API spec.

I'm not entirely sure this is something we want to cover with this library since we're trying to adhere to the specification as closely as possible.
