### ISSUE TITLE
Bad include can return 500

### ISSUE THREAD

**Issue by MarkESDR** [jeregrine/jsonapi#134]
According to the includes spec on jsonapi ([1](http://jsonapi.org/format/#fetching-includes)), invalid includes should only return 400.

https://github.com/jeregrine/jsonapi/blob/242499eaf42362fa0f1e6602ecc08f9baa7feaad/lib/jsonapi/query_parser.ex#L183

Looks to be due to this line. Based on whether or not the atom exists in the app, the line raises an error only on certain invalid includes

**Comment by doomspork** [comment]
@MarkESDR could you provide a repo that produces this error?  I think that would be easiest to work from.  Do you happen to have a solution in mind?

**Comment by MarkESDR** [comment]
@doomspork [Here](https://github.com/MarkESDR/jsonapi_issue_134) is an example repo. For solutions,  how about, instead of converting the request include param to an atom to compare, converting the list of valid include params to strings. This allows us to compare the request params and valid params without creating extra atoms

**Comment by doomspork** [comment]
@MarkESDR we'd love a PR to fix this if you have the time 👍
