### ISSUE TITLE
Non-standard source for a relationship

### ISSUE THREAD

**Issue by kbaird** [jeregrine/jsonapi#136]
Hi. Let's say I have a `Product`, with a `tag_ids` field of type `{:array, :string}`.

I'd like to construct a normal-appearing `tags` relationship in my `ProductView`, such that the `tags` derive not from a regular `has_many` relationship, but rather any `Tag` whose uuid primary_key is in that `product.tag_ids` array.

Is there any reasonable way to do this?

**Comment by kbaird** [comment]
In case anyone's curious, a potential solution:
`field :tags, {:array, :map}, virtual: true`

```
  def inject_tags_from_tag_ids(product) do
    tag_ids = product.tag_ids || []
    tags = for id <- tag_ids, do: %{id: id}
    %{product | tags: tags}
  end
```

Then adding `tags: {TagView, :include}` to `relationships` in the View seems to work OK.

**Comment by jeregrine** [comment]
This will work temporarily. I think a solution for this might be to allow
view functions to override relationships as well to pre-process them.

But I'm open to suggestions for this api as you're use case isn't unique
and we'll likely see it come up again.

**Comment by kbaird** [comment]
Just spitballing on things that would've seemed easier to me.

here's one idea:
```
def relationships do
  [
    # other entries...
    tags: {:tag_ids, &tag_from_id/1}
  ]
end

defp tags_from_ids(tag_ids) do
  for id <- tag_ids, do: %{id: id, type: "tags"}
end
```

The idea being that `:tag_ids` is the name of the field that is the source of the data, and `&tags_from_ids/1` is the function to transform said data.

**Comment by kbaird** [comment]
You could also lock it down more with
```
def relationships do
    [
    # other entries...
    tags: [ids: :tag_ids, type: "tags"]
  ]
end
```

That's less flexible, intended only for an input that is known to be a list of IDs (as is true for us).

I prefer the other example with a function arg, personally.

**Comment by kbaird** [comment]
FYI, this is no longer a priority for our specific project.

**Comment by jherdman** [comment]
Ha! I was just contemplating this issue. Many thanks for the heads up. I'll close this issue then.
