### ISSUE TITLE
Links Usage Unclear

### ISSUE THREAD

**Issue by jherdman** [jeregrine/jsonapi#141]
I've read over the docs and have done my best to grok the code, but I'm a bit confused on how to specify links.

Suppose I want to include a link for a Book's many Pages, I might want something like this:

```json
{
  "data": {
    "id": 123,
    "title": "Curious George"
  },
  "relationships": {
    "pages": {
      "self": "/api/book/123/relationship/pages"
// snip
```

Setting up my `BookView` isn't quite clear to me. If I override `links/2` it doesn't seem to do anything. Overriding `relationships/0` as so doesn't seem to work:

```elixir
def relationships do
  [pages: PageView]
end
```

I think I may be missing something obvious, but I could use a hand.

**Comment by doomspork** [comment]
@jherdman can you expand on what "doesn't seem to work" means?  Is it throwing an error?  Is the generated JSON missing fields?

It could be that you're not preloading the relationship information.  Have you tried preloading the association in Ecto?  

Additionally, you can use `:include` in the relationships function (which is mentioned in the README) to ensure the relationship is always included in the response:

```elixir
def relationships do
  [pages: {PageView, :include}]
end
```

**Comment by jherdman** [comment]
Hey Sean!

I've successfully sideloaded data via :include, bit have yet to generate
links, eg for a has many relationship. Does this still require preloading
data? If so, this seems a bit backwards. The URL is always knowable
regardless of data being available at serialization time. So, no errors are
thrown, it's just that I can't figure out how to include links for
relationships.

**Comment by jherdman** [comment]
OK, here's a concrete example:

```elixir
defmodule DailyBugleWeb.SubscriptionView do
  use JSONAPI.View, type: "subscriptions", namespace: "/api"

  alias DailyBugleWeb.SourceView

  def fields do
    [
      :inserted_at
    ]
  end

  def relationships do
    [
      source: {SourceView, :include}
    ]
  end
end
```

This clearly includes the `SourceView` if the `Source` has been preloaded. But what if I want to include a link by default (e.g. request hasn't asked for the Source to be included)?

**Comment by jherdman** [comment]
A more concrete example of a valid JSON:API use case: https://github.com/jherdman/jsonapi/commit/6adfa5f967cd5de8ef636ecd21f5f9104d029b29.
