### ISSUE TITLE
Add camelCase member names option

### ISSUE THREAD

**Issue by ahx** [jeregrine/jsonapi#142]
Since https://github.com/json-api/json-api/pull/1297, JSONAPI now recommends using `camelCase` member names: https://jsonapi.org/recommendations/#naming

It's a SHOULD, but it would be nice to have an option in the Configuration or JSONAPI.EnsureSpec.

**Comment by snewcomer** [comment]
@ahx Great idea!  Would that be something you would like to tackle?  If not, I have time next week. Namely, we have `underscore_to_dash` as a configuration option currently.  I would imagine we add a configuration option `camel_case` and default it to `false` for now.  What do you think?

**Comment by ahx** [comment]
Sounds like a plan.
I will try to make a PR, but my Elixir skills are still very low, so don’t wait for me.

**Comment by snewcomer** [comment]
@ahx No worries on the skill level!  If you created a PR, we can both contribute to that branch.  Just let me know as we can work through it together.  Or I can get your review on a PR.  Either way is fine with me.

**Comment by snewcomer** [comment]
I have a WIP on this so far.  Waiting for resolution of #137 before doing any more work though 👍

**Comment by ahx** [comment]
@jherdman using camelCase is just a recommendation and not a MUST and it's not linked to a specific version of the JSON:API specification. So it is totally valid to stick with dash-case even if supporting the upcoming JSON:API 1.1. Implementors should be able to choose whatever they want.

**Comment by jherdman** [comment]
Resolved by #158
