### ISSUE TITLE
Meta field should not be nil

### ISSUE THREAD

**Issue by snarkitect** [jeregrine/jsonapi#143]
It seems like we may be handling the top level "meta" member incorrectly in 0.8. 
A [top level document](https://jsonapi.org/format/#document-top-level) must have one of "data", "errors", and "meta" with some caveats. 

When "meta" is included, it must be a ["meta" object](https://jsonapi.org/format/#document-meta).

We're looking to update from 0.7 to 0.8 for the fixes made representing empty relationships, but we're hesitant to update our tests to respect "nil" meta value if that isn't compliant with the JSON:API spec. I'd hate to have to update them again if this is fixed.

**Comment by snewcomer** [comment]
@snarkitect I believe you are referring to this PR.  If so, you could point to a specific commit or master.  I think a new release is in order at some point.

https://github.com/jeregrine/jsonapi/pull/124

**Comment by snarkitect** [comment]
That looks like it should solve the issue. I was just updating our project to use 0.8 from 0.7 and didn't see that PR. Thanks for the quick response!
