### ISSUE TITLE
[RFC] Tweak Utils.Underscore Module

### ISSUE THREAD

**Issue by jherdman** [jeregrine/jsonapi#153]
Proposal
---------

* `Utils.Underscore` module should be renamed `Utils.String` — it exclusively operates on Strings and this new name makes way for eventually offering camelization and decamelization without a confusing name.
* `Utils.Underscore.dash/1` and `Utils.Underscore.underscore/1` should change names. The current names are confusing: `dash/1` replaces dashes with underscores, and `underscore/1` replaces dashes with underscores. Other libraries (e.g. Rails, Ember) also use `dasherize`. Aligning with these libraries eases the barrier to entry for new users.

Concerns
-----------

* This is a breaking change to a public API
* Merge conflicts for WIP PRs

Possible Mitigation Pathways
-----------------------------

Introduce a module using the proposed named, `Utils.String`, and use the new method names. The current module, `Utils.Underscore`, will point to these methods and include a deprecation warning. This would allow us to safely do a minor release.

Alternatives
------------

### Replaces `Utils.Underscore` with Inflex

[Inflex](https://github.com/nurugger07/inflex) is a library that offers String manipulation functions that could replace _part of_:

* `Utils.Underscore.underscore` with `Inflex.dash`
* `Utils.Underscore.dash` with `Inflex.parameterize(term, "-")`
* And even supplies `Inflex.camelize`

We could replace the String manipulation functions in `Utils.Underscore` with said methods, leaving in place utilities for traversing objects (e.g. changes added in #149 to traverse params and underscore them). Said utilities could be moved to a `Utils.Parameters` module.

#### Advantages

* Inflex is fleshed out and tested. We wouldn't have to maintain such functions going forward.
* Above mitigation pathway still applies

#### Concerns

* We lose control over these methods. Future changes with Inflex may not map to our needs, or even what we need exactly.
* Above concerns still apply

#### Open Questions

I'll try to get answers for these ASAP:

- [x] Are Inflex's transformations 100% compatible with our own? E.g. does `underscore/1` work _exactly_ like `parameterize(term, "-")`?
- [x] License concerns?
- [x] Similar libraries that we should investigate?

**Comment by snewcomer** [comment]
I like this.  Also could consider maybe some methods from `inflex` would be useful to do some of our work - https://github.com/nurugger07/inflex

**Comment by jherdman** [comment]
@snewcomer I've added a preliminary "Alternatives" section with Inflex. I'll need to do some more homework on the lib, but it looks promising!

**Comment by jherdman** [comment]
Inflex Findings
--------------

`Inflex.underscore/1` to replace `Underscore.dash/1` fails two tests:

```
  1) doctest JSONAPI.Utils.Underscore.dash/1 (3) (JSONAPI.Utils.UnderscoreTest)
     test/utils/underscore_test.exs:8
     Doctest failed
     code:  dash("-top--posts-") === "-top--posts-"
     left:  "_top__posts_"
     right: "-top--posts-"
     stacktrace:
       lib/jsonapi/utils/underscore.ex:21: JSONAPI.Utils.Underscore (module)

  2) doctest JSONAPI.Utils.Underscore.dash/1 (2) (JSONAPI.Utils.UnderscoreTest)
     test/utils/underscore_test.exs:8
     Doctest failed
     code:  dash("-top-posts") === "-top_posts"
     left:  "_top_posts"
     right: "-top_posts"
     stacktrace:
       lib/jsonapi/utils/underscore.ex:18: JSONAPI.Utils.Underscore (module)
```

`Inflex.parameterize("-", value)` to replace `Underscore.underscore/1` fails three tests:

```
  1) doctest JSONAPI.Utils.Underscore.underscore/1 (10) (JSONAPI.Utils.UnderscoreTest)
     test/utils/underscore_test.exs:8
     Doctest failed
     code:  underscore("top_posts") === "top-posts"
     left:  "top_posts"
     right: "top-posts"
     stacktrace:
       lib/jsonapi/utils/underscore.ex:76: JSONAPI.Utils.Underscore (module)

  2) doctest JSONAPI.Utils.Underscore.underscore/1 (11) (JSONAPI.Utils.UnderscoreTest)
     test/utils/underscore_test.exs:8
     Doctest failed
     code:  underscore("_top_posts") === "_top-posts"
     left:  "_top_posts"
     right: "_top-posts"
     stacktrace:
       lib/jsonapi/utils/underscore.ex:79: JSONAPI.Utils.Underscore (module)

  3) test when underscore_to_dash == true serialize properly uses underscore_to_dash on both attributes and relationships (JSONAPISerializerTest)
     test/serializer_test.exs:372
     Assertion with == failed
     code:  assert attributes["full-description"] == data[:full_description]
     left:  nil
     right: "This_is_my_description"
     stacktrace:
       test/serializer_test.exs:395: (test)
```

I think this possibly rules out Inflex as an option unless we want to change behaviour as well. I'm not a fan of this personally given the contractual nature of HTTP APIs.

**Comment by doomspork** [comment]
Since we haven't cut a new release now would be the time to make more breaking changes. I vote we keep the functionality within our lib and do the module changes proposed above by @jherdman

**Comment by jherdman** [comment]
@doomspork to clarify: are you arguing for the change to be breaking, or shall I include the mitigation pathway as well?

**Comment by snewcomer** [comment]
@jherdman Yeah I am not sure inflex is what we want b/c we specialize it like so - `String.replace(value, ~r/([a-zA-Z0-9])-([a-zA-Z0-9])/, "\\1_\\2")` - by replacing only in b/w two words.  Was more thinking of inflex for camelCase, which I have a PR in progress for.

**Comment by jherdman** [comment]
If there are no objections I'm going to go ahead and implement the above using the mitigation pathway. This will let us cut 0.9 to at least give people some warning about this change, and do a broader clean up 1.0 release.

**Comment by doomspork** [comment]
> @doomspork to clarify: are you arguing for the change to be breaking, or shall I include the mitigation pathway as well?

I'm not _arguing_ anything 😁 

Due to other breaking changes in this release I think we can do without a migration pathway as we did not provide such a thing for the underscore/dash changes.
