### ISSUE TITLE
Project Discussion

### ISSUE THREAD

**Issue by jeregrine** [jeregrine/jsonapi#154]
First of all I want to thank everyone for all the work thats gone into JSONAPI in the last few months. I reeally appreciate it and the time you've invested.

Secondly I want to apologize for not being as available.

**Action items:**

- Could @snewcomer and @doomspork signup for hex.pm and then somehow send me your hex.pm email? (irc, email, twitter DM preferred) I will add you as owners so you can cut releases without me. Also if you have a mailing address you aren't afraid to share I would also like to send you a thank you gift. :-)
- Recently we've gotten a ton of contributions from @jherdman which is awesome! Would you (@jherdman) like to be an "official" maintainer of this project?

Lemme know if there is anything else I can do to make everyone's lives easier. And also JSONAPI better. :P

**Comment by doomspork** [comment]
@jeregrine sounds good, email sent to your RokkinCat address (only one I have).

**Comment by jeregrine** [comment]
Alright @doomspork and @snewcomer have package rights for this. Feel free to release new versions, if you'd like I can tweet about it just lemme know. 

@jherdman lemme know if you'd like to be an official contributor and I'll see to it.

**Comment by jherdman** [comment]
@jeregrine I'd love to be! Many thanks.

**Comment by jeregrine** [comment]
Done! Happy to have you
