### ISSUE TITLE
Can't figure out how to use field_name/2 for sparse fieldsets

### ISSUE THREAD

**Issue by kbaird** [jeregrine/jsonapi#156]
I've been reading the docs, and found `You can define custom fields or override current fields by defining inside the view function field_name/2 that takes data and conn as arguments.` at https://hexdocs.pm/jsonapi/JSONAPI.View.html#module-fields

I've tried defining `field_name/2` on my pertinent view module, but it seems to be ignored when `fields/0` is present, and `fields/0` being absent produces the error from https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/view.ex#L138.

Is there any guidance I'm missing on how to comply with https://jsonapi.org/format/#fetching-sparse-fieldsets?

**Comment by kbaird** [comment]
Oh, I see. `field_name` is a meta-variable. So if you have a field called `foobar`, you need to define `def foobar(data, conn), do: ...` in your view module.

That said, I still don't see how to truncate the list of fields based on the request. I don't want `nil` (otherwise modified values) for a given field name - I want the field name to be absent entirely, which seems to be what the spec prescribes.

**Comment by jherdman** [comment]
@jeregrine is this your intention in #120?
