### ISSUE TITLE
Release Planning

### ISSUE THREAD

**Issue by jherdman** [jeregrine/jsonapi#157]
During work on #155 and #149 the concern of breaking changes came up. I'd like to suggest we do a little release planning to clarify direction on this, and other PRs in the work. I'm opening this meta issue so as to collect needs/wants.

Proposal
---------

- Cut a 0.9 release that merely adds new features on top of 0.8, replete with deprecation warnings for changes (e.g. the upcoming #155, #149, and other existing warnings)
- Shortly thereafter cut a 1.0 release that's 0.9 with all deprecated code removed

Planning
--------

- [ ] Will the addition of #142 affect either the proposed 0.9 release or 1.0?
- [ ] Issue triage:
  - [ ] Outstanding bugs that should be tackled before a 0.9 release?
  - [ ] Close any open stagnant issues?
- [ ] Any areas of improvement that should be captured or resolved before a 1.0 release?

**Comment by jherdman** [comment]
I'm going to go ahead and start this today. Please feel free to triage issues accordingly.

**Comment by snewcomer** [comment]
Seems likely that #158 will necessitate a 1.0 release as I have gotten into it.  

The only other addition for post 1.0 is v1.1 [profile-links](https://jsonapi.org/format/1.1/#profile-links)
