### ISSUE TITLE
[RFC] Improve Linked Relationship Handling

### ISSUE THREAD

**Issue by jherdman** [jeregrine/jsonapi#169]
## Problem Statement

Inclusion of a relationship in a payload is determined by its presence in the data. This is problematic for relationships with large numbers of members.

## Proposal

1. Introduce a shorthand for always including a given relationship as a link: `:link`. See Examples below.
2. Make the implicit explicit by introducing an option for a relationship tuple: `:optional`. This option is merely to indicate the current behaviour is desired. A deprecation warning will be raised should a relationship handling option not be present.

## Examples

The following would use the current behaviour and would result in a deprecation warning.

```elixir
def relationships() do
  [author: AuthorView]
end

# Deprecation:

"relationship `author` for `mytype` is defined without an explicit handling option. To maintain current behaviour please define as: `author: {AuthorView, :optional}`"
```

Whereas this would not:

```elixir
def relationships() do
  [
    dealerships: {DealershipView, :optional}
  ]
end
```

The following is an example of the new behaviour:

```elixir
def relationships() do
  [
    author: {AuthorView, :link}, # NEW! link is always included
    books: {BookView, :include}, # CURRENT BEHAVIOUR
    payments: {PaymentView, :optional} # CURRENT BEHAVIOUR
  ]
end
```

## Open Questions

- [ ] Dynamically determining whether or not to include a relationship is currently not handled. Is this desirable?

**Comment by snewcomer** [comment]
@jherdman Sparsely included relationships have been something I have worked with in the past.  I guess you could consider this analogous to sparse [fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets).  Is this an option?

**Comment by snewcomer** [comment]
e.g. in the relationships block.  Is at least the id && type available in the scenario you laid out?

```
{
  "id": "11234",
  "type": "user",
  "href": "..."
}
```

**Comment by jherdman** [comment]
@snewcomer I hadn't considered that, no. I'm poking around through the specification to find an example like the one you have above, but I'm struggling to find an example. The closest I've found is:

```
"relationships": {
  "author": {
    "links: {
      "self": "http://example.com/authors/1"
    },
    "data": {
      "type": "person",
      "id": 9
    }
  }
},
"included": [{
  "type": "person",
  "id": 9,
  "attributes": {
    // etc
```

Is that what you're referring to?

**Comment by snewcomer** [comment]
> Inclusion of a relationship in a payload is determined by its presence in the data. This is problematic for relationships with large numbers of members.

I guess what is the problem right now (perhaps stated differently)?  I wasn't totally sure after reading this and perhaps might be missing some context.  What is the need for a `link` option?

**Comment by snewcomer** [comment]
I see.  Great explanation.  So w/ lots of relationships, the user has a few options:

1.  Pagination
3. No pagination w/ `include` && w/o `preload` - which sounds like the case you are talking about??

Is this somewhat of a specialized case?  Perhaps this should simply be the fallback without any extra annotation in the view layer?

**Comment by jherdman** [comment]
> Perhaps this should simply be the fallback without any extra annotation in the view layer

A concern I have with this is that it'd be a breaking change necessitating a major release. This isn't necessarily a problem, but it doesn't really offer us an ergonomic way to build towards it (e.g. introduce deprecations or safe upgrade path).

Maybe the solution is to take a sneak peak at another RFC I wanted to open. Another problem with `relationships/0` is that the only way to filter out relationships is by the presence or absence of the data. We may want to include or exclude relationships for user roles (e.g. admins or customer service reps may have more access). Introducing `relationships/2` that accepts `data` and `conn`. We could always deprecate `relationships/0` and introduce fully new behaviour for ONLY this implementation.

**Comment by snewcomer** [comment]
> A concern I have with this is that it'd be a breaking change necessitating a major release.

One reason why I thought we could by default include was b/c it seems the paradigm was to include unless [remove_links](https://github.com/jeregrine/jsonapi#configuration) is set to false. Initially, I thought this would be a minor bump.  What would be breaking?

Also, how does one get the included resource (override?) when the view specifies `:link`?  Or is that not possible?

**Comment by jherdman** [comment]
@snewcomer I think you're onto something here. OK, here's a summary of my thoughts right now:

* `:include` means that we embed the relationship by default IF the data has been loaded
* by default we always have a relationship link — this is net new behaviour
* an unsolved problem, then, is how to include, or exclude, relationships for a given current user

I'm going to close this proposal and submit a brand new one to introduce `relationships/2` — something that would offer us a clean upgrade path.

> ... the paradigm was to include unless [remove_links](https://github.com/jeregrine/jsonapi#configuration) is set to false...

Isn't `remove_links` only for the top-level `:links` object, and not a given relationship link? I.E...

```javascript
{
 "id": 123,
  "type": "book",
  "data": {
    // etc.
  },
  "relationships": {
    "author": {
      "self": "http://example.com/books/123/relationships/author"  // NOT THIS
    },
  "links": {
    "self": "http://example.com/books/123" // BUT THIS
  }
}
```

**Comment by snewcomer** [comment]
@jherdman I'll wait for your new proposal! 

Looks** like the [test](https://github.com/jeregrine/jsonapi/blob/01bd057b2d6ef14825b0bd248696778729288ece/test/serializer_test.exs#L532) is looking at various levels.
