### ISSUE TITLE
[RFC] Rework Relationships

### ISSUE THREAD

**Issue by jherdman** [jeregrine/jsonapi#174]
## Summary

Relationship handling in the `View` layer is closely tied to the presence of data for a given relationship. This need not be the case when data isn't being sideloaded.

## Motivation

By removing the coupling between data presence and link inclusion we reduce overhead, and have a clearer API for relationship linking.

## Detailed Design

Let's introduce an overridable `relationships/1` method that is preferentially used when serializing to build the `"relationships"` object in a response. This method has the following signature:

```elixir
@spec relationships(conn :: Plug.Conn.t()) :: keyword()
```

In providing the `conn` argument we offer the ability for consumers of this library to prune, or add, relationships based upon, for instance, a current user.

In this method any and all configured relationships will have a link by default. Configured relationships will be sided loaded if, and only if, requested by the client (thus the `QueryParser` must be in play). A new option, `:embed`, will be introduced. This option is the same as `:include` — data will be embedded in the `"included"` object if, and only if, the associated data has been loaded.

In introducing this method we'll deprecate `relationships/0` with the intent of removing it in our next major release.

## Drawbacks

Additional `Serializer` and `View` complexity. We may need to do some refactoring here to reduce cognitive overhead whilst maintaining both pathways.

## Alternatives

- We could do nothing. The current implementation works.
- We willingly introduce a breaking change. The use case above wherein I talk about pruning a relationship for a user of lower privilege, for instance, might be better served with an entirely new view instead.

## Unresolved Questions

- [ ] I've reached out to @jeregrine regarding why we wanted the associated data to be loaded in the first place. This decision goes quite a ways back: b8bc80c5549bb7bb07934da762d888504365f90e. There may be really good reasons for this that I'm missing.
- [x] Should `data` be provided to the new `relationships` method too? I can't really see why it would be needed, and I feel like it's best to constrain whatever we add as much as possible. One advantage of doing so would be that edge cases like #136 could be resolved (though I'm not entirely sure how this would fit in with the JSON:API spec).

**Comment by jherdman** [comment]
* Updated with a new alternative
* I'm going to spike out an implementation of this RFC for more discussion

**Comment by strzibny** [comment]
I would also like to be able to provide a custom relationship response when the API options are not what needs to be done (just ability to provide a different struct that will turn to JSON).

**Comment by jherdman** [comment]
@strzibny can you provide an example of your ideal outcome?

**Comment by strzibny** [comment]
@jherdman So this issue is only about relationships, but I will explain the whole story. On the API I work right now I would like to provide a "minimalist" JSON:API.

That means:
- no `data` in relationship objects (or possibly only in has one)
- no relationship self links
- only relationship related links

If you think about it this is still full JSON:API spec API, but it's pretty minimal, easy to work with and document. So that's my goal. Right now I am close to finish it with jsonapi + ja_serializer that replaces the view part. I wish I can use jsonapi (as a single dependency) all the way, but it's not flexible enough whereas ja_serializer can omit data easily in relationship (just omit the view parser and no data shows) and it's flexible for links and pagination too.

**Comment by jherdman** [comment]
I'm closing this, but I have renewed interest in finally resolving this problem. It's pretty clear to me this library has serious problems with both relationships and links. More to come soon.

**Comment by jeregrine** [comment]
@jherdman looking forward to it

**Comment by jherdman** [comment]
That'd be great! The other part of the puzzle I couldn't figure out was how to roll this out in a backwards compatible way. It may be easiest, however, just to roll it out and cut a new major.
