### ISSUE TITLE
Setting content-type

### ISSUE THREAD

**Issue by 0urobor0s** [jeregrine/jsonapi#184]
When I render a view the content-type header is set to ``application/json`` but I'm using the Plug ``JSONAPI.EnsureSpec`` in the pipeline.
I think the problem is that phoenix is setting the header, but I don't know where. And then the Plug does not update the header which is the expect behavior. 
Also, I know it is working properly because when make an invalid request the header is set correctly to ``application/vnd.api+json``

**Comment by jherdman** [comment]
Try adding the `JSONAPI.ResponseContentType` to your pipeline. I think this will resolve the problem. If it does we may need to consider adding it to the `EnsureSpec` pipeline.

**Comment by 0urobor0s** [comment]
Nice, that indeed solved the problem.
Should I make a PR?

**Comment by jherdman** [comment]
That'd be greatly appreciated, many thanks!
