### ISSUE TITLE
[RFC] Overhaul of JSONAPI From top to Bottom

### ISSUE THREAD

**Issue by jeregrine** [jeregrine/jsonapi#19]
So I am putting together this gist of ideas on how we can better structure the library to be less ad-hoc. I realize now that only doing a view layer really limits you to what's possible with JSONAPI. So I've put together a sort of happy path in this gist https://gist.github.com/jeregrine/b57827f36e4d70116540. Please comment here so the conversation stays in one place. 

The basic idea is we start at the top and build up a JSONAPI configuration that can be used to validate the request, build queries, build data, and render data. This also gives us a base data structure we can use to build simple scaffolding so you can get spun up with jsonapi/phoenix/ecto very quickly, and without complex and opaque macro's.

So let me know what you think! All 7 of you watchers :)

**Comment by alexjp** [comment]
Hi,

Sorry i have been away, i took a quick look at the RFC, and seems interesting. I understand that one can add or remove custom data from the view only, using standard query builder and query parser.

Will this "auto magic" make responses much slower ?

How can i help?

Thanks !!!

**Comment by jeregrine** [comment]
@alexjp well it should not effect it greatly. Each step will be a plug so you can skip a step and do it yourself.

**Comment by jeregrine** [comment]
If you are curious as to how it's coming the QueryParser is coming along and with one more test I will have it finished. 

https://github.com/jeregrine/jsonapi/compare/overhaul#diff-4ff2056ce272293cfbc7a72bdcf44ffbR6

I will probably work on next building an ecto query from the configuration.

**Comment by jeregrine** [comment]
Heads up here. Overhaul branch is coming soon. Major changes include 

- Relationships is an array of type, [View, {View, :include}]
- Fields are an array of atoms you want to include from the base model, as well as fields you want to be request able from the query string.
- New url functions that provide sane defaults, and can be overridable. 
- Fully unit tested. 
- Fully integration tested (WIP)
- Fully Documented (WIP)
- Full query parser plug that handles 100% of the jsonapi query parsing abilities and turns it into elixir datastructures so you can work with it, and build queries with it. 
- Not going to add Ecto query building in this release. 

Things todo still: 
- Re-add Paging or ability
- Build example app.

**Comment by alexjp** [comment]
Sorry for the absence...

@jeregrine I will test it and create some emberjs apps

**Comment by jeregrine** [comment]
@alexjp that would be perfect! Let me know here or on IRC if you have any issues. Can fix them fast.

**Comment by alexjp** [comment]
@jeregrine if interested add this project as an example on the README.MD of overhaul branch:
```
https://github.com/alexjp/jsonapi-testing
```

I will keep the project updated to test jsonapi features. Interested in a pull request ?

**Comment by jeregrine** [comment]
Closing this. Please view the PR/WIP
