### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by dwarner** [jeregrine/jsonapi#190]
I know at first this is going to come across as a jerk issue I'm submitting . . . but it is hard to find anybody referencing this project by searching for `jsonapi`.  Sure, you can add `elixir` or a few other terms, but that still doesn't narrow it down enough to be accurate.  A project should have a branded and distinguishable name from the tech it is implementing.

**Comment by jherdman** [comment]
I think that's reasonable feedback, but we're definitely not alone here: https://jsonapi.org/implementations/. That doesn't make it a great reason to keep the name, but it does at least mean we're not alone.

For what it's worth I think the spec has a lousy name. If I don't follow the spec but still use JSON to handle the communication between my client and server am I using any less of a JSON API? 😆

**Comment by doomspork** [comment]
@dwarner appreciate the thought, definitely don't think you're a jerk 😁 

However, I think it's unrealistic to change the name 4 years into the project. Deprecating a whole package to append `_ex` to it is kind of silly if you don't mind my saying. We can ask @jeregrine to add labels to the repo to make it easier to locate in the Github search but I don't think changing the package name is something in our future. 

Furthermore, I'm not sure Google or Github are the place to search for Elixir dependencies. Hex.pm has that built in and just search "jsonapi" yields this project at the top as well as other implements: https://hex.pm/packages?_utf8=%E2%9C%93&search=jsonapi&sort=recent_downloads

**Comment by dwarner** [comment]
@jherdman Yeah, the spec didn't do us any favors with their name.

I didn't notice the "License" had an initial commit of 4 years ago!  Nice.

@doomspork The use case I'm talking about isn't finding the package in the first place.  Being new to Elixir/Phoenix, I often will look to see if their is a tutorial using that specific package. Or did somebody reference it on the Elixir forum or StackOverflow.

I totally get not putting effort into renaming, but thought I would throw it out there. Thanks for the response and for the hard work on the project.

**Comment by jeregrine** [comment]
Closing this as its not gonna happen, appreciate the frustration.
