### ISSUE TITLE
JSONAPI.Page struct attrs parsed as strings

### ISSUE THREAD

**Issue by lucacorti** [jeregrine/jsonapi#191]
Apparently the `JSONAPI.Page` in conn assigns contains strings from the request parameters, but the typespecs define the struct attrs as `non_neg_integers`.

```
[debug] Processing with UsersWeb.UsersController.index/2
  Parameters: %{"page" => %{"page" => "1", "size" => "10"}}
  Pipelines: [:jsonapi]
```

```
%JSONAPI.Page{
  cursor: nil,
  limit: nil,
  offset: nil,
  page: "1",
  size: "10",
  total_items: nil,
  total_pages: nil
}
```

**Comment by jherdman** [comment]
Interesting. Some questions:

- If we retain these values as Strings and adjust the typespecs accordingly are we losing anything?
- Are we gaining anything by casting these values to integers?

**Comment by lucacorti** [comment]
I think there is value into parsing these values into integers, I'm going to elaborate on this in my PR.

**Comment by jherdman** [comment]
IMHO to simplify the implementation of your PR let's solve this bug independently.

**Comment by lucacorti** [comment]
I think the best thing is to parse them as integers.

**Comment by lucacorti** [comment]
I update #189 with a fix.

**Comment by lucacorti** [comment]
I am closing this as I believe the `JSONAPI.Page` in intrinsically broken. I've updated #189 to remove it, which I think is a better solution and doesn't need added configuration to support arbitrary query parameter names and parsing values.
