### ISSUE TITLE
Deserializer

### ISSUE THREAD

**Issue by denniscastro** [jeregrine/jsonapi#210]
Hi,

The Serializer works fine. but I would like to know if there is any plan to implement Deserializer module?, If not, What do you recommend to use for it?

**Comment by jeregrine** [comment]
You mean take a jsonapi document and hydrate some a model graph?

**Comment by hernanvicente** [comment]
@jeregrine probably @denniscastro did mean something like this:

```ruby
# Gemfile
gem 'jsonapi-rails'

# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  deserializable_resource :post, only: [:create, :update]

  def create_params
    params.require(:post).permit(:title, :content, :tag_ids)
  end

  def create
    post = Post.create(create_params)
    render jsonapi: post,
           include: [:author, comments: [:author]],
           fields: { users: [:name, :email] },
           status: :created
  end
end
```

I would be interested too to know if there is a recommended way to accomplish something similar with this package?

**Comment by jgelens** [comment]
https://github.com/vt-elixir/ja_serializer/blob/master/lib/ja_serializer/params.ex has a nice way to deserialize all the attributes and relations.

**Comment by jherdman** [comment]
OK, that seems pretty interesting. Would you be interested in putting together an RFC that proposes a solution?

**Comment by snewcomer** [comment]
This was one thing I missed in past projects when I moved from ja_serializer to jsonapi.  I've generally used it as a plug to flatten the incoming params for changeset casting.

```js
def parse_data(%{"data" => data}), do: JaSerializer.Params.to_attributes(data)
```

So I like this idea!

**Comment by jgelens** [comment]
The code can be used as-is. Just add the copyright according to JASerialiver license and rename the module to match JSONAPI?

**Comment by doomspork** [comment]
@jgelens interested in tackling this for Hacktoberfest?

**Comment by psteininger** [comment]
I have user https://github.com/vt-elixir/ja_resource/ in the past, and found it quite useful. It seems like development on this kind of stopped a year ago or even more. It was a really clever way to build a complete JSONAPI stack. The only thing missing for me was handling submitting objects with child entities all at once, be it through side-posting or breaking the spec and including `data` in relationships.

**Comment by doomspork** [comment]
@psteininger we're open to PRs if someone wanted to take a crack at implementing the deserializer functionality for this package :+1:

**Comment by snewcomer** [comment]
@psteininger @denniscastro We do have an `UnderscoreParameters` plug you can add to your controller pipeline!  Does that help you?

**Comment by snewcomer** [comment]
Upon further thought @denniscastro was this what you were getting at?  Effectively taking a jsonapi document and making it easy for changeset casting...

https://github.com/jeregrine/jsonapi/pull/223#issuecomment-592794415
