### ISSUE TITLE
Migrate Build Process to Github Actions

### ISSUE THREAD

**Issue by jherdman** [jeregrine/jsonapi#225]
It seems like there's a bit of a broader push to migrate from Travis to Github Actions. With Covid-19 going around I thought this might be a nice time to give this a shot. Any objections?

**Comment by doomspork** [comment]
I'm up for it. I've moved most of my projects to it and it's been great. You can take a peek at the Guardian CI file, it's probably got most of what we need: https://github.com/ueberauth/guardian/blob/master/.github/workflows/ci.yml

**Comment by jherdman** [comment]
Resolved by #226 and #227
