### ISSUE TITLE
JSONAPI.org Errors Spec

### ISSUE THREAD

**Issue by nicholaswyoung** [jeregrine/jsonapi#32]
The JSONAPI Spec documents define how [errors should be handled](http://jsonapi.org/format/#error-objects), but I don't see helpers in this module. Should I create a pull request, or is it already handled and I missed it?

I know that additional keys are optional, but it might be nice to bake in a couple of conventions.

**Comment by jeregrine** [comment]
@nicholaswyoung That would be awesome!

**Comment by nicholaswyoung** [comment]
@jeregrine What portion of the spec recommendations do you think are the most important? Or should we just roll with all of the "MAY" recommendations as we can?

**Comment by jeregrine** [comment]
@nicholaswyoung I focus on should but may is nice to have :)

**Comment by doomspork** [comment]
Working on this here: https://github.com/doomspork/jsonapi/tree/feature/errors
