### ISSUE TITLE
String.to_atom considered unsafe on untrusted, external data

### ISSUE THREAD

**Issue by KronicDeth** [jeregrine/jsonapi#34]
The use of `String.to_atom` is considered unsafe because it can fill the global atom table.  Places where `String.to_atom` now could be changed to `String.to_existing_atom`, which should only allow atoms for known relationships and fields that have already been loaded, in `JSONAPI.QueryParser` and elsewhere.  If using `String.to_existing_atom` doesn't work, because all the fields and relationships might not be an atom anywhere else, you would have to keep all the data as `String`s until the application using the library can validate if it is safe to convert to atoms.  Either of these should mitigate the Denial of Service potential of flooding of the atom table.

**Comment by jeregrine** [comment]
Good call. If you wanna PR it I would gladly accept. Otherwise I might not be able to get to this till later.
