### ISSUE TITLE
Custom URL in links?

### ISSUE THREAD

**Issue by mfunaro** [jeregrine/jsonapi#35]
Is there a way to customize the links that get built? 

My resource is set up in the router.ex like this...

```Elixir
 scope "/api", Handiman do
   pipe_through :api

   resources "/users", UserController, except: [:new, :edit, :create]
   resources "/register", RegistrationController, only: [:create]
   resources "/rounds", RoundController, except: [:new, :edit]
  end
```

so my URLs will look like `/api/rounds` but when the links are created for 'self' for example, `api` is not included and the URL is useless.

**Comment by mpriestman** [comment]
I've managed to work around this by providing implementations of `url_for/2` in my view that return the correct URL for the resource. It's a bit messy, but it works. Maybe there is a better way?
