### ISSUE TITLE
Allow to set meta

### ISSUE THREAD

**Issue by gottfrois** [jeregrine/jsonapi#56]
Would be nice to allow to set meta for each resources. Something like this I imagine:

```
# message_view.ex
defmodule Foo.MessageView do
  def meta
    %{ count: Message.count, unread_count: Message.unread_count_for(params[:id]) }
  end
end
```

Not sure how we can pass the "params" in there though. Any thoughts?

**Comment by jeregrine** [comment]
@gottfrois it's definitely not supported at the moment.

But I would love to accept a PR to the serializer.ex and the view.ex. I like your api but I'd prefer if the meta function accepted a conn. 

If you check out this function https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/serializer.ex#L11 it starts the process. You'd need to add meta here and have it call `meta: view.meta(conn, data)` and have a default `view.ex` meta function that returns an empty %{} and is overrideable.

If you'd be willing to take this on it would be amazing!

**Comment by gottfrois** [comment]
Sounds good, I'm an elixir learner so bare with me :)

**Comment by jeregrine** [comment]
@gottfrois not a problem :-)

**Comment by doomspork** [comment]
@gottfrois any updates on this?  I'd love to evaluate using this lib but we need the meta portion before we can do so 😁

**Comment by sebbean** [comment]
what would you need to take a crack at this addition @doomspork ?

**Comment by doomspork** [comment]
@sebbean I just want to ensure neither @gottfrois or @jeregrine has started work on this, I don't want to step on anyone's toes.  If they haven't I can put up a PR 😁

**Comment by jeregrine** [comment]
Noboy has done anything as far as I can tell. All PRs happily accepted.
