### ISSUE TITLE
Please release an updated version to hex.pm

### ISSUE THREAD

**Issue by jonathanperret** [jeregrine/jsonapi#57]
Thank you for `jsonapi`! Unfortunately, the current version on hex.pm (0.3.0) does not contain the latest significant change (removal of `PhoenixView`, which is a bit confusing. Could you upload a new release?

**Comment by jeregrine** [comment]
@jonathanperret Thanks for poking me, updated to 0.4.0!

**Comment by jonathanperret** [comment]
Thanks 👍
