### ISSUE TITLE
Rename and compose fields

### ISSUE THREAD

**Issue by SxDx** [jeregrine/jsonapi#61]
Is ist possible to define custom field names?
I am working with a legacy database that has inconsistent column names that I don't want to expose over the api, e.g. I want to transform `columnName` to `column_name`.

Additionally I would like to combine multiple database columns to a single `key: value` pair.

**Comment by jeregrine** [comment]
@SxDx it's not well documented but in your JSONAPI Views you can override a function called "attributes" and have it return a map of the exact attributes you want to return. As shown here https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/view.ex#L84

The default implementation is just a simple `Map.take(model, fields())`
