### ISSUE TITLE
Handling URL generation w/hosts other than whats stored in `conn`

### ISSUE THREAD

**Issue by ybur-yug** [jeregrine/jsonapi#64]
This might have a bad title, apologies.

So, we just deployed our serialization layer redone in JSONAPI! Its great.
However, we noticed one weird tidbit and wondered if you thought it would be something that might be able to be handled at the library level, or if there may be something in our configuration that we need to work around.

What we are having occur is that our `host` on our `conn` is getting set as 0.0.0.0 due to the way we run the binary in production. We obviously would like the links we send to be real/working, and reflect the actual hostname of the machine etc on which the things are hosted on.

We could make a simple plug that sets the hostname from a configuration and have no changes here, but I havent researched if changing that in our `conn` could impact anything else.

It could be an option to add a `host` argument to `url_for/2` and customize the behaviour.

Tbqh I am not sure what the best way to handle things would be, but it didnt seem like it would break any current behaviour or really change the exposed API if we added the option to pass your own host. But this also could be a bit of a band-aid and we really just should configure out own things better.

Thoughts?

Thanks Again for the awesome work!

**Comment by jeregrine** [comment]
This is a good question. I think maybe having an optional configuration would be best, we could see if its set and use it over `conn.host`

**Comment by ybur-yug** [comment]
@jeregrine cool, I'll make a PR

**Comment by bmrsny** [comment]
PR: [#66](https://github.com/jeregrine/jsonapi/pull/66)

**Comment by doomspork** [comment]
This was closed via #66
