### ISSUE TITLE
Hidden fields

### ISSUE THREAD

**Issue by doomspork** [jeregrine/jsonapi#68]
@jeregrine curious to get your thoughts on whether this is a feature we want or something I should keep in my application.  There are a few instances in which we need to include a field in our view so it can be posted or patched but we don't want it included in the response (think passwords).  For this I've implemented a `hidden/0` that works like `fields/0` but is used to hide certain values from the response.

Is this something you'd be open to considering?  If so I'll open a PR.

**Comment by jeregrine** [comment]
definitely not against it. I wonder if maybe we can do it in the fields method. Say having a field like 

[:email, {:password, :hidden}]

Either way I will defer to your judgment

**Comment by doomspork** [comment]
Hmm.  That's a good point.  I will give both a whirl and ping you on a PR for thoughts 👍

**Comment by doomspork** [comment]
Here's the implementation for these two different approaches, which do you prefer @jeregrine?  

We'll need to update `attributes/1`: 

```elixir
def attributes(data, conn) do
  data = visible_fields(data)

  if underscore?() do
    underscore(data)
  else
    data
  end
end
```

With that change, here are the two implementations:

```elixir
# JSONAPI.View
def hidden, do: []

defp visible_fields(data), do: Map.take(data, fields() - hidden())

# MyApp.View
def fields, do: [:first_name, :last_name, :password, :username]
def hidden, do: [:password]
```

```elixir
# JSONAPI.View
defp visible_field?({field, :hidden}), do: false
defp visible_field?(field), do: true

defp visible_fields(data), do: Map.filter(fields(), &visible_fields?/1)

# MyApp.View

def fields, do: [:first_name, :last_name, {:password, :hidden}, :username]
```

**Comment by Dto47** [comment]
@jeregrine https://react-bootstrap-table4.github.io/2EzEcmD/
