### ISSUE TITLE
how to parse incoming json?

### ISSUE THREAD

**Issue by InteNs** [jeregrine/jsonapi#76]
Hey, I'm trying to use this library for parsing json data that i fetch from an external json api.
I couldn't find a proper example for this so i tried this myself.
```Elixir
defmodule JsonApi do
  use Tesla

  plug Tesla.Middleware.BaseUrl, "www.example.com"
  plug Tesla.Middleware.Headers, %{"Authorization" => "hidden"}
  plug JSONAPI.QueryParser

  def get do
    get("/asset-types/locomotives/")
  end
end
```

the issue is that tesla has 3 arguments for plugs, and jsonapi only expects 2.

is there any chance for a Tesla compatible plug for requesting json?
or is there a better way to parse json requested from external api(without phoenix)?

**Comment by jeregrine** [comment]
Sorry @InteNs  I didn't really write the de-serializer for parsing JSONAPI into structs. This libarary is largely focusing on serializing elixir objects into JSONAPI compatible formats.

The Query Parser takes a url that meets the jsonapi query standard so for example `GET /article/5/?include=user,comment.user&fields[article]=title%2Cbody&page[limit]=20&sort=-created" would parse the information after the `?` and return it as a map you can use for an echo query. 

I would happily entertain a de-serializer its just more nuanced than a typical de-serializer. Your best bet would be  `Poison.decode` it into a map and go from there. The JSONAPI spec is pretty straight forward.

**Comment by InteNs** [comment]
ah, completely misunderstood this package then ;) sorry about that

**Comment by jeregrine** [comment]
@InteNs no problem!
