### ISSUE TITLE
Optional data configuration

### ISSUE THREAD

**Issue by snewcomer** [jeregrine/jsonapi#81]
Option to not include data could help speed things up.  

- self
- links
- included

https://github.com/code-corps/code-corps-api/issues/1139

I'll work on a PR if everyone agrees this is a good idea!

**Comment by jeregrine** [comment]
@snewcomer This seems like a good idea. Since links are an optional part of the JSONAPI spec. I'd accept it. Just make sure its configured application wide.

**Comment by snewcomer** [comment]
Ref #82
