### ISSUE TITLE
Index views do not list `self` in links

### ISSUE THREAD

**Issue by StareIntoTheBeard** [jeregrine/jsonapi#83]
http://jsonapi.org/format/#document-links
Unless I'm reading something wrong, is it not required to show a self link under index views as well as show views?

Seems like a change here would fix the issue:
https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/serializer.ex#L25

**Comment by jeregrine** [comment]
@StareIntoTheBeard you appear to be correct. Would you be willing to take this one on?

**Comment by StareIntoTheBeard** [comment]
@jeregrine Sure, happy to.

**Comment by jeregrine** [comment]
Thank!

**Comment by StareIntoTheBeard** [comment]
https://github.com/jeregrine/jsonapi/pull/84 @jeregrine
