### ISSUE TITLE
Feature Request - custom attribute method

### ISSUE THREAD

**Issue by snewcomer** [jeregrine/jsonapi#89]
If I define methods in my `**view.ex` file, I want to include them in the attributes hash.  Once could imagine combining `first + last` or some type of conditional logic for a specific field at the view layer.

I was wondering your thoughts were on this and if it is something you want me to take a stab at...

```
defmodule MyApp.ArticleSerializer do

  def fields, do: [:body, :excerpt]

  def excerpt(article, _conn) do
    [first | _ ] = String.split(article.body, ".")
    first
  end
end
```

**Comment by snewcomer** [comment]
@doomspork @jeregrine Hey just pinging again.  Would definitely love to contribute a PR if needed!

**Comment by jeregrine** [comment]
@snewcomer totally would accept a PR for this. Idea makes sense for me.

**Comment by snewcomer** [comment]
@jeregrine Looking at `view.ex`, I'm trying to decide how to approach this.  If each field is specified as an atom, perhaps instead of [take](https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/view.ex#L146), we can look throug each attr and if it doesn't exist in `data`, we can try calling a function.

Or we could convert each attribute to a function itself.  So anytime you ask for that attribute, it calls a function.  Defining a function like `excerpt` above is simply overriding the defined function.

Any thoughts on a good approach to this?

**Comment by jeregrine** [comment]
I don't mind that route at all. I do worry we might see some overhead, but
its probably minimal.

**Comment by doomspork** [comment]
My only concern with this approach is that if you define a function with the same name as a key in your data, it would not be used.  How about something like this?

```elixir

def visible_fields(data) do
  visible_fields = fields() -- hidden()

  Enum.map(visible_fields, fn field ->
    if function_exported?(__MODULE__, field, 1) do
      apply(__MODULE__, field, [data])
    else
      Map.get(data, field)
    end
  end)
end
```

**Comment by jeregrine** [comment]
:+1:

**Comment by doomspork** [comment]
It might be worth doing a little benchmarking on this to see what is the best option.  Another could be to try the `apply/3` call and capture the argument error if it doesn't exist.

```elixir
def fields(data) do
  visible_fields = fields() -- hidden()

  Enum.map(visible_fields, fn field ->
    try do
      apply(__MODULE__, field, [data])
    rescue
      _e -> Map.get(data, field)
    end
  end)
end
```
