### ISSUE TITLE
Improper checking of headers

### ISSUE THREAD

**Issue by TrevorHinesley** [jeregrine/jsonapi#90]
In [this](https://github.com/jeregrine/jsonapi/blob/1f9e45aee4058ca6b3a8a55aaec6eebcada525a6/lib/jsonapi/plugs/content_type_negotiation.ex) file, it forces the headers to conform to the JSONAPI media type improperly.

To [quote](http://jsonapi.org/format/#content-negotiation-servers):

```
Servers MUST send all JSON API data in response documents with the header Content-Type: application/vnd.api+json without any media type parameters.
```

The server MUST respond with the proper headers, the library handles this okay.

```
Servers MUST respond with a 415 Unsupported Media Type status code if a request specifies the header Content-Type: application/vnd.api+json with any media type parameters.
```

This seems to be worded intentionally, such that **if** a request specifies the `Content-Type: application/vnd.api+json` header **with** any additional parameters, it should return a 415. The server itself is not required to force the client to send the `Content-Type: application/vnd.api+json` header (just to enforce that it's done properly if the client does send it), though [the client is required by the spec to send it](http://jsonapi.org/format/#content-negotiation-clients).

```
Servers MUST respond with a 406 Not Acceptable status code if a request’s Accept header contains the JSON API media type and all instances of that media type are modified with media type parameters.
```

This also seems to be worded intentionally, such that **if** a request specifies an `Accept` header with the proper type, but ALL instances of that media type are modified (meaning it can have multiple media types, and even multiple declarations of the JSONAPI media type), throw a 406. Again, the server is not required to force the client to send the `Accept: application/vnd.api+json` header (just to enforce that it's done properly if the client does send it -- and only to enforce it if they use the `application/vnd.api+json` media type, **and each time it's specified** it has modified media type parameters), and actually, [_the client isn't required to send this header at all, they're just required to **not** modify the media type with parameters on at least one instance of it if they do pass it_](http://jsonapi.org/format/#content-negotiation-clients).

Just wanted to clarify that. Great library!

**Comment by doomspork** [comment]
@TrevorHinesley thank you for bringing this to our attention!  Would you like to open a PR for this?

**Comment by TrevorHinesley** [comment]
You're welcome! If I can get some time to do it soon, I will. I doubt I will though, if someone else has any time to tackle it. Elixir isn't my current language, I was actually researching and learning when I saw this in this repo and just thought I'd help out!

**Comment by snewcomer** [comment]
I can tackle this by the end of the week.

**Comment by doomspork** [comment]
Thanks @snewcomer 👍
