### ISSUE TITLE
Thoughts on publishing a new release?

### ISSUE THREAD

**Issue by snewcomer** [jeregrine/jsonapi#95]
@doomspork @jeregrine Thanks for the awesome attention to this lib!  I think you were thinking about cutting a new release after this PR: https://github.com/jeregrine/jsonapi/pull/92

**Comment by doomspork** [comment]
@snewcomer sorry I know @jeregrine has been busy and I was supposed to do that.  I'll get to that this week 👍

**Comment by jeregrine** [comment]
Thanks for the reminder!

**Comment by pmyjavec** [comment]
@jeregrine anything we can help with to make this happen?

**Comment by doomspork** [comment]
@pmyjavec apologizes mate but we're both very busy (I've been out of the country without a computer for some time), 'tis the nature of open source.  Please have patience.

There is nothing preventing you from using the package today:

```elixir
{:jsonapi, github: "jeregrine/jsonapi"}
```
